#! /bin/bash

scriptTokBin=/full/path/to/hotspot-distr/ScriptTokenizer/src/script-tokenizer.py
pipeDir=/full/path/to/hotspot-distr/pipeline-scripts
tokenFile=runall.tokens.txt

## Download test data if necessary
data=test_DNase_seq.hg19.bam
url=http://www.uwencode.org/proj/hotspot/$data
if [ ! -s $data ]; then
    echo "downloading test data..."
    wget $url
fi

## Do SPOT only (set _FDRS_ to "N" in runall.tokens.txt)
# scripts="$pipeDir/run_make_lib
#     $pipeDir/run_10kb_counts
#     $pipeDir/run_pass1_hotspot
#     $pipeDir/run_pass1_merge_and_thresh_hotspots
#     $pipeDir/run_pass2_hotspot
#     $pipeDir/run_rescore_hotspot_passes
#     $pipeDir/run_spot"

## Do everything, including badspots and final cleanup
scripts="$pipeDir/run_badspot
    $pipeDir/run_make_lib
    $pipeDir/run_wavelet_peak_finding
    $pipeDir/run_10kb_counts
    $pipeDir/run_generate_random_lib
    $pipeDir/run_pass1_hotspot
    $pipeDir/run_pass1_merge_and_thresh_hotspots
    $pipeDir/run_pass2_hotspot
    $pipeDir/run_rescore_hotspot_passes
    $pipeDir/run_spot
    $pipeDir/run_thresh_hot.R
    $pipeDir/run_both-passes_merge_and_thresh_hotspots
    $pipeDir/run_add_peaks_per_hotspot
    $pipeDir/run_final"

$scriptTokBin \
    --clobber \
    --output-dir=`pwd` \
    $tokenFile \
    $scripts

for script in $scripts
do
    ./$(basename $script).tok
done
